package com.cf.cfsecurity.dao.model;

import java.util.Date;

public class CfResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.RES_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String resId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.DESCN
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String descn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.URL
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.PARENT_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.ISLEAF
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private Boolean isleaf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.ENABLED
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private Boolean enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.CREATOR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_resource.CREATE_DATE
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.RES_ID
	 * @return  the value of cf_resource.RES_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getResId() {
		return resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.RES_ID
	 * @param resId  the value for cf_resource.RES_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setResId(String resId) {
		this.resId = resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.DESCN
	 * @return  the value of cf_resource.DESCN
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getDescn() {
		return descn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.DESCN
	 * @param descn  the value for cf_resource.DESCN
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setDescn(String descn) {
		this.descn = descn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.URL
	 * @return  the value of cf_resource.URL
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.URL
	 * @param url  the value for cf_resource.URL
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.PARENT_ID
	 * @return  the value of cf_resource.PARENT_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.PARENT_ID
	 * @param parentId  the value for cf_resource.PARENT_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.ISLEAF
	 * @return  the value of cf_resource.ISLEAF
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public Boolean getIsleaf() {
		return isleaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.ISLEAF
	 * @param isleaf  the value for cf_resource.ISLEAF
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setIsleaf(Boolean isleaf) {
		this.isleaf = isleaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.ENABLED
	 * @return  the value of cf_resource.ENABLED
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.ENABLED
	 * @param enabled  the value for cf_resource.ENABLED
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.CREATOR
	 * @return  the value of cf_resource.CREATOR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.CREATOR
	 * @param creator  the value for cf_resource.CREATOR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_resource.CREATE_DATE
	 * @return  the value of cf_resource.CREATE_DATE
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_resource.CREATE_DATE
	 * @param createDate  the value for cf_resource.CREATE_DATE
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}