package com.cf.cfsecurity.dao.model;

import java.util.Date;

public class CfRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role.ROLE_NAME
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role.DESCR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String descr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role.ENABLED
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private Boolean enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role.CREATOR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role.CREATE_DATE
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role.ROLE_ID
	 * @return  the value of cf_role.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role.ROLE_ID
	 * @param roleId  the value for cf_role.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role.ROLE_NAME
	 * @return  the value of cf_role.ROLE_NAME
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role.ROLE_NAME
	 * @param roleName  the value for cf_role.ROLE_NAME
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role.DESCR
	 * @return  the value of cf_role.DESCR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getDescr() {
		return descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role.DESCR
	 * @param descr  the value for cf_role.DESCR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role.ENABLED
	 * @return  the value of cf_role.ENABLED
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role.ENABLED
	 * @param enabled  the value for cf_role.ENABLED
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role.CREATOR
	 * @return  the value of cf_role.CREATOR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role.CREATOR
	 * @param creator  the value for cf_role.CREATOR
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role.CREATE_DATE
	 * @return  the value of cf_role.CREATE_DATE
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role.CREATE_DATE
	 * @param createDate  the value for cf_role.CREATE_DATE
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}