package com.cf.cfsecurity.dao.model;

public class CfRoleResourceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role_resource.RES_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String resId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_role_resource.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role_resource.RES_ID
	 * @return  the value of cf_role_resource.RES_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getResId() {
		return resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role_resource.RES_ID
	 * @param resId  the value for cf_role_resource.RES_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setResId(String resId) {
		this.resId = resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_role_resource.ROLE_ID
	 * @return  the value of cf_role_resource.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_role_resource.ROLE_ID
	 * @param roleId  the value for cf_role_resource.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
}