package com.cf.cfsecurity.dao.model;

public class CfUserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_user_role.USER_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cf_user_role.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_user_role.USER_ID
	 * @return  the value of cf_user_role.USER_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_user_role.USER_ID
	 * @param userId  the value for cf_user_role.USER_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cf_user_role.ROLE_ID
	 * @return  the value of cf_user_role.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cf_user_role.ROLE_ID
	 * @param roleId  the value for cf_user_role.ROLE_ID
	 * @mbggenerated  Thu Jun 27 15:36:25 CST 2013
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
}