package com.cf.cfsecurity.dao.model;

public class SysDictKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.GROUP_ID
     *
     * @mbggenerated Mon Jul 15 14:09:07 CST 2013
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.DICT_VALUE
     *
     * @mbggenerated Mon Jul 15 14:09:07 CST 2013
     */
    private String dictValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.GROUP_ID
     *
     * @return the value of sys_dict.GROUP_ID
     *
     * @mbggenerated Mon Jul 15 14:09:07 CST 2013
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.GROUP_ID
     *
     * @param groupId the value for sys_dict.GROUP_ID
     *
     * @mbggenerated Mon Jul 15 14:09:07 CST 2013
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.DICT_VALUE
     *
     * @return the value of sys_dict.DICT_VALUE
     *
     * @mbggenerated Mon Jul 15 14:09:07 CST 2013
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.DICT_VALUE
     *
     * @param dictValue the value for sys_dict.DICT_VALUE
     *
     * @mbggenerated Mon Jul 15 14:09:07 CST 2013
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }
}